language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=travis
services:
  - mongodb
notifications:
  email:
    recipients:
      - chaines@gmail.com
  irc:
    channels:
      - "irc.freenode.org#devict"
  slack: thelaborparty:F8sIulfJ68UaZ3NhteTx1mu7
  on_success: always # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
